calibration json
iqm-finland/cirq-on-iqm pull request #17
Opened 2021-06-02 18:33 UTC by dc914337

adds calibrating settings file

2021-06-03 11:03 UTC, manevala requested changes

2021-06-03 11:03 UTC, manevala commented on src/cirq_iqm/iqm_client.py
>              "mapping": qubit_mapping,
And with that corrected, the demo fails with another error.

2021-06-03 17:44 UTC, dc914337 commented on src/cirq_iqm/iqm_client.py
fixed linter, there is a known bug: https://github.com/samuelcolvin/pydantic/issues/1961

2021-06-04 11:10 UTC, dc914337 commented on src/cirq_iqm/iqm_client.py
>              "mapping": qubit_mapping,
demo fails due to the backend errors

2021-06-09 09:09 UTC, merged